### ISSUE TITLE
Repository ownership

### ISSUE THREAD

**Issue by nordicdyno** [ostrovok-team/pgdump-obfuscator#5]
I'm considering this repo as useful piece of code, but disturbed that nobody owns it. My suggestion to @temoto is to take ownership or move code to any place where it could have some love (like merged on time PRs).

**Comment by vanadium23** [comment]
Sorry for the long wait. I don't think this is a good idea. 
That was wrong preference for notifications in my account, so I will merge PRs faster.
Is it ok? :)

**Comment by nordicdyno** [comment]
It would be great!

**Comment by rromanchuk** [comment]
👍
